#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG SHADOW HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// Test-only shadow code: production firmware does not include this header.
// =============================================================================

#include <cstddef>
#include <string>

enum class CardContractShadowPolicyKind { KEEP, CLEAR, DEFAULT_VALUE, ALLOWED, ALIAS, HOOK };
struct CardContractShadowFieldPolicy { const char *field; CardContractShadowPolicyKind policy; const char *detail; };

inline const CardContractShadowFieldPolicy SAVED_CONFIG_SHADOW_ACTION_FIELDS[] = {
  {"entity", CardContractShadowPolicyKind::KEEP, ""},
  {"label", CardContractShadowPolicyKind::KEEP, ""},
  {"icon", CardContractShadowPolicyKind::HOOK, "normalize_action_fields"},
  {"icon_on", CardContractShadowPolicyKind::HOOK, "normalize_action_fields"},
  {"sensor", CardContractShadowPolicyKind::HOOK, "normalize_action_fields"},
  {"unit", CardContractShadowPolicyKind::HOOK, "normalize_action_fields"},
  {"type", CardContractShadowPolicyKind::HOOK, "normalize_action_fields"},
  {"precision", CardContractShadowPolicyKind::HOOK, "normalize_action_fields"},
  {"options", CardContractShadowPolicyKind::HOOK, "normalize_action_options"},
};

inline const CardContractShadowFieldPolicy SAVED_CONFIG_SHADOW_SENSOR_FIELDS[] = {
  {"entity", CardContractShadowPolicyKind::KEEP, ""},
  {"label", CardContractShadowPolicyKind::KEEP, ""},
  {"icon", CardContractShadowPolicyKind::HOOK, "normalize_sensor_fields"},
  {"icon_on", CardContractShadowPolicyKind::HOOK, "normalize_sensor_fields"},
  {"sensor", CardContractShadowPolicyKind::HOOK, "normalize_sensor_fields"},
  {"unit", CardContractShadowPolicyKind::KEEP, ""},
  {"type", CardContractShadowPolicyKind::DEFAULT_VALUE, "sensor"},
  {"precision", CardContractShadowPolicyKind::HOOK, "normalize_sensor_fields"},
  {"options", CardContractShadowPolicyKind::HOOK, "normalize_sensor_options"},
};

inline const CardContractShadowFieldPolicy SAVED_CONFIG_SHADOW_MEDIA_FIELDS[] = {
  {"entity", CardContractShadowPolicyKind::KEEP, ""},
  {"label", CardContractShadowPolicyKind::HOOK, "normalize_media_fields"},
  {"icon", CardContractShadowPolicyKind::HOOK, "normalize_media_fields"},
  {"icon_on", CardContractShadowPolicyKind::KEEP, ""},
  {"sensor", CardContractShadowPolicyKind::HOOK, "normalize_media_fields"},
  {"unit", CardContractShadowPolicyKind::KEEP, ""},
  {"type", CardContractShadowPolicyKind::DEFAULT_VALUE, "media"},
  {"precision", CardContractShadowPolicyKind::HOOK, "normalize_media_fields"},
  {"options", CardContractShadowPolicyKind::HOOK, "normalize_media_options"},
};

inline const CardContractShadowFieldPolicy SAVED_CONFIG_SHADOW_VACUUM_FIELDS[] = {
  {"entity", CardContractShadowPolicyKind::KEEP, ""},
  {"label", CardContractShadowPolicyKind::KEEP, ""},
  {"icon", CardContractShadowPolicyKind::HOOK, "normalize_vacuum_fields"},
  {"icon_on", CardContractShadowPolicyKind::DEFAULT_VALUE, "Auto"},
  {"sensor", CardContractShadowPolicyKind::ALLOWED, "start_stop"},
  {"unit", CardContractShadowPolicyKind::HOOK, "normalize_vacuum_fields"},
  {"type", CardContractShadowPolicyKind::DEFAULT_VALUE, "vacuum"},
  {"precision", CardContractShadowPolicyKind::CLEAR, ""},
  {"options", CardContractShadowPolicyKind::CLEAR, ""},
};

inline const char *const SAVED_CONFIG_SHADOW_VACUUM_MODES[] = {"status", "start_stop", "dock", "pause_resume", "clean_spot", "locate", "clean_area"};
inline const char *const SAVED_CONFIG_SHADOW_VACUUM_UNIT_MODES[] = {"clean_area"};

inline bool saved_config_shadow_string_in(const std::string &value, const char *const *values, size_t count) {
  for (size_t index = 0; index < count; ++index) if (value == values[index]) return true;
  return false;
}

inline const char *saved_config_shadow_vacuum_icon(const std::string &mode) {
  if (mode == "dock") return "Robot Vacuum Variant";
  if (mode == "clean_spot") return "Vacuum";
  if (mode == "locate") return "Robot Vacuum Alert";
  if (mode == "clean_area") return "Vacuum Outline";
  return "Robot Vacuum";
}

template<typename Config>
inline bool normalize_saved_config_vacuum_shadow(Config &config) {
  if (config.type == "action" && config.sensor == "vacuum.start") { config.type = "vacuum"; config.sensor = "start_stop"; }
  if (config.type == "action" && config.sensor == "vacuum.return_to_base") { config.type = "vacuum"; config.sensor = "dock"; }
  if (config.type != "vacuum") return false;
  if (!saved_config_shadow_string_in(config.sensor, SAVED_CONFIG_SHADOW_VACUUM_MODES, sizeof(SAVED_CONFIG_SHADOW_VACUUM_MODES) / sizeof(SAVED_CONFIG_SHADOW_VACUUM_MODES[0]))) config.sensor = "start_stop";
  config.type = "vacuum"; config.icon_on = "Auto"; config.precision.clear(); config.options.clear();
  if (!saved_config_shadow_string_in(config.sensor, SAVED_CONFIG_SHADOW_VACUUM_UNIT_MODES, sizeof(SAVED_CONFIG_SHADOW_VACUUM_UNIT_MODES) / sizeof(SAVED_CONFIG_SHADOW_VACUUM_UNIT_MODES[0]))) config.unit.clear();
  if (config.icon.empty() || config.icon == "Auto") config.icon = saved_config_shadow_vacuum_icon(config.sensor);
  return true;
}
